# Generated by Django 3.1.3 on 2020-11-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0002_auto_20201122_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Fday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='Tday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='memo',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
